<h2>Add product</h2>

<form method="POST" enctype="multipart/form-data" id="add">
    <fieldset>
        <div class="add-name">
            <label for="name">Name</label>
            <input type="text" name="name" id="name"/>
        </div>
        <div class="add-description">
            <label for="description">Description</label>
            <textarea name="description" id="description" ></textarea>
        </div>
        <div class="add-price">
            <label for="price">Price</label>
            <input type="text" id="price" name="price">
        </div>
        <div class="add-file">
            <label for="photo">Photo</label>
            <input type="file" name="photo">
        </div>
        
        
    </fieldset>
    <button class="add-btn">Add</button>
</form>