<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<h2>Carte du restaurant</h2>
<table class="generic-table meal-list">
    <tbody>
        <?php foreach($products as $product):?>
        <tr>
            <td><img src="<?= $wwwUrl ?>/images/meals/<?= htmlspecialchars($product['image'] )?>"></td>
            <td>
                <h3> <?= htmlspecialchars($product['name'])?></h3>
                <p> <?= htmlspecialchars(substr($product['description'],0,150))?>...</p>
            </td>
            <td> <p><?= htmlspecialchars($product['price']) ?> €</p></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>