<h2>Order</h2>
<section class="order">

    <div class="product">
        <h3>Product</h3>
        <div class="style-select">
            <select name="product-name" id="product-name">
            
                <?php 
                    for($i = 0; $i <count($products); $i++)
                    { ?>
                        <option value="<?= $products[$i]['id'] ?>"><?= htmlspecialchars($products[$i]['name']) ?></option>
                    <?php } ?>
            </select>
            <i class="fas fa-arrow-down"></i>
        </div>
        <div class="info">
            <div class="img">
                
            </div>
           
            <div>
                <p class="description"></p>
                <p class="price"></p>
                
            </div>
        </div>
            <div class="quantity">
                
            </div>
        
        <button  class="order-btn">Add</button>
        
    </div>
    <div class="basket">
        <div class="top-basket">
            <img src="<?= $wwwUrl ?>/images/btn-order.png"></img>
        </div>
        <div class="basket-bottom">
            <div class="basket-order">
            
            </div>
        </div>
    </div>
</section>


<script src="<?= $wwwUrl ?>/js/order.js"></script>